Add Jira support
dougsland/bz-query pull request #12
Opened 2022-08-03 17:29 UTC by ricky-rav

Refactored code and added support for jira queries (bugs and escalations)

Signed-off-by: Riccardo Ravaioli <rravaiol@redhat.com>

2022-08-03 17:30 UTC, ricky-rav commented
/assign @flavio-fernandes

2022-08-03 20:05 UTC, flavio-fernandes requested changes
A few more tweaks to the readme install, please.

2022-08-03 20:05 UTC, flavio-fernandes commented on README.md
> +$ git clone https://github.com/dougsland/bz-query && pushd bz-query
@ricky-rav I think we need to refine the install a little more.
I tried followoing the steps described here and end up with this error:
```
env ❯ ./network_bugs_overview -h
Traceback (most recent call last):
  File "/home/vagrant/dev/douglas_bugzilla/tmp/bz-query/./network_bugs_overview", line 8, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'
```

How about we create a file called requirements.txt with the dependencies we need:

```
jira
python-dateutil
```

and the as part of the install add `pip install .`

2022-08-04 13:57 UTC, flavio-fernandes requested changes
hm.... I'm getting this error below. Maybe I'm doing something wrong?

.env ❯ git rev-parse HEAD
eb958cf203c11c4c9209bf9592f0b73d3249cc4a

Also, can you please format the python code with black:
```
pip install black
black network_bugs_overview
```
?

```
.env ❯ ./network_bugs_overview  --jira-bugs
Error running JIRA query project=OCPBUGS and component in ("networking/openshift-sdn", "networking/ovn-kubernetes", "networking") and status in ("NEW", "ASSIGNED", "POST", "ON_DEV", "In Progress"), error: Unterminated string starting at: line 1 column 145102 (char 145101)
- Found 0 bugs with the query: project=OCPBUGS and component in ("networking/openshift-sdn", "networking/ovn-kubernetes", "networking") and status in ("NEW", "ASSIGNED", "POST", "ON_DEV", "In Progress")
  Query processing time: 0.8s
  ```

2022-08-04 13:57 UTC, flavio-fernandes commented on README.md
> +- bugzilla for existing bugs (the creation new bugs will soon be disabled on our bugzilla server),
nit: white space in the end of this line

2022-08-04 19:46 UTC, dougsland commented
@ricky-rav @flavio-fernandes awesome patch. +1 for merge it for now. However, as it's getting `pro-level` :)  Should we move to an `official team repo` somewhere?

2022-08-05 09:01 UTC, ricky-rav commented
> @ricky-rav @flavio-fernandes awesome patch. +1 for merge it for now. However, as it's getting `pro-level` :) Should we move to an `official team repo` somewhere?

no rush for now, I think :)

2022-08-05 09:04 UTC, ricky-rav commented
@flavio-fernandes I ran black on the source file and applied your requested changes.

Also, after clarifying this with the team yesterday, I removed from the default behaviour the queries to the RHOCPPRIO project in Jira. We'll see, as we get more familiar with jira bugs, what escalated bugs in OCPBUGS project will look like, how to include them, and whether we will use RHOCPPRIO issues at all.

2022-08-25 13:39 UTC, dougsland commented
looks good :) @flavio-fernandes ?

2022-08-25 14:29 UTC, flavio-fernandes commented
/lgtm!

2022-08-25 14:30 UTC, merged